[package]
name = "blestooo/dataservice"
version = "0.2.0"
description = "A clean and simple to use data handler & replicator"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.3"
Networker = "leifstout/networker@0.3.0"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"